
# server-port
server:
  port: 8084
  
# application-name
spring:
  application:
    name: API-GATEWAY
    
# cloud-gateway
  cloud:
    gateway:
    
# cloud-gateway-routes
      routes:
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
#        - Path=/api/user/**
        - Path=/user/**
      
      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
#        - Path=/api/hotel/**
        - Path=/hotel/**,/staff/**
        
      - id: RATING-SERVICE
        uri: lb://RATING-SERVICE
        predicates:
#        - Path=/api/rating/**
        - Path=/rating/**


          
    
# eureka-server
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka