
# server-port
server:
  port: 8082
#  servlet:
#    context-path: /api
       
# datasource
spring:
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: root
    
# -- spring.config.import.optional:configserver:http://localhost:8085
  config:
    import:
    - optional:configserver:http://localhost:8085
    
# jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

## eureka
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka    
#    
    
    
    
    