
# server-port
server:
  port: 8081
#  servlet:
#    context-path: /api
       
# datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    
# jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
# change-default-application-name
  application:
    name: USER-SERVICE
    
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect

# eureka
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  
      
    
    
    
    
    